#!/bin/bash

echo "{ \"version\": 1, \"title\": \"Commands\", \"type\":\"commands\", \"values\" : [ {\"name\" : \"Process list\", \"value\" : \"\", \"command\" : \".pilotssh/process/process.sh\" }, {\"name\" : \"Apache services\", \"value\" : \"\", \"command\" : \".pilotssh/apache/apache.sh\" }, { \"name\" : \"logs\", \"value\" : \"\", \"command\" : \".pilotssh/logs/logs.sh\"}, {\"name\" : \"Power\", \"value\" : \"\", \"command\" : \".pilotssh/power/power.sh\"}, {\"name\" : \"Echo\", \"value\" : \"\", \"command\" : \".pilotssh/echo/echo.sh\", \"query\": \"Echo?\" } ] }";
