#!/bin/bash

dirs=( $(find * -type d | sort) )

result='{ "version": 1, "title": "Commands", "type":"commands", "values" : ['
first=$dirs
result=$result"{\"name\":\"$first\", \"value\":\"\", \"command\":\".pilotssh/$first/$first\" }"
unset dirs[0]

for dir in "${dirs[@]}"; do
  result=$result", {\"name\":\"$dir\", \"value\":\"\", \"command\":\".pilotssh/$dir/$dir\"}"
done

result=$result" ]}"

echo $result

