#!/bin/bash

echo '{ "version": 1, "title": "System", "type":"commands", "values" : [ {"name" : "Manage cron", "value" : "", "command" : ".pilotssh/system/crontab.sh }, {"name" : "Free cache", "value" : "", "command" : ".pilotssh/system/free_cache.sh } ] }';
