#!/usr/bin/env sh

if [ "$#" -ne 1 ]
then
  echo '{ "version": 1, "title": "Echo", "type":"status", "status":"error", "message":"Please enter something" }';
else
  echo "{ \"version\": 1, \"title\": \"Echo\", \"type\":\"commands\", \"values\" : [ { \"name\" : \"Echo\", \"value\" : \"$1\", \"command\" : \"\"} ] }";
fi
